from enum import Enum


class SMBStatus(str, Enum):
    STATUS_SUCCESS              = "STATUS_SUCCESS"
    STATUS_LOGON_FAILURE        = "STATUS_LOGON_FAILURE"
    STATUS_ACCOUNT_LOCKED_OUT   = "STATUS_ACCOUNT_LOCKED_OUT"
    STATUS_ACCOUNT_DISABLED     = "STATUS_ACCOUNT_DISABLED"
    STATUS_PASSWORD_EXPIRED     = "STATUS_PASSWORD_EXPIRED"
    STATUS_PASSWORD_MUST_CHANGE = "STATUS_PASSWORD_MUST_CHANGE"
